server:
  port: 8082

spring:
  application:
    name: my-second-service

eureka:
  client:
    register-with-eureka: true # defaultZone(EurekaServer)에 EurekaClient를 등록한다.
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
